package com.github.economicaircompany.model;

import java.util.List;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;

//With @Entity we're saying to Spring that this Class
//is a SQL database table

//Airport is the ONLY class in this system which is FREE:
//SQL speaking it doesn't have Foreign Keys pointing to
//another table
//But other tables have foreign keys targetting airport
//(The table Flight references to airport, indeed!!!)

@Entity
public class Airport {

    // Here we say: "Spring, this id is a SQL column named "id..."
    @Id
    // "...and the value of this column will be auto-generating
    // and auto-incrementing (1,2,3,4...)"
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // This is a SQL column
    @Column
    private String name;

    @Column
    private String country;

    @Column
    private String city;

    @Column
    private String airportCode;

    // Things getting serious here:
    // This means: there is 1 airport, but there are MANY flights
    // having this airport as departure or arrival!!!
    // this is why: one--> to --->many
    // SEE class Flight for more!

    @OneToMany
    private List<Flight> flights; // list beacuse there are MANY flights using this airport(which is ONE)

    // We will need and empty constructor
    public Airport() {
    }

    // Costructor without id (it will be generated by SQL automaticcaly
    // because of line 27)

    public Airport(String name, String country, String city, String airportCode, List<Flight> flights) {
        this.name = name;
        this.country = country;
        this.city = city;
        this.airportCode = airportCode;
        this.flights = flights;
    }

    // Creating getters and setters
    // right click-->source action-->Generate Getters and Setters))

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getAirportCode() {
        return airportCode;
    }

    public void setAirportCode(String airportCode) {
        this.airportCode = airportCode;
    }

    public List<Flight> getFlights() {
        return flights;
    }

    public void setFlights(List<Flight> flights) {
        this.flights = flights;
    }

}
